src/ui/atoms/SeriesMathChip.md
src/ui/layouts/DataPointInspectorDrawer.md
src/ui/layouts/InspectorHeader.md
src/ui/organisms/AttributeZone.md
src/ui/organisms/CardinalityCapsule.md

- add spec for DataPointInspectorDrawer layout
- document InspectorHeader layout
- create AttributeZone and CardinalityCapsule organism specs
- add SeriesMathChip atom spec

Add inspector drawer module specs

---

src/index.tsx.md

- document app bootstrap and event listeners in `index.tsx.md`

Add index entrypoint documentation

---

src/hooks/useInspectorProps.md

- update `useInspectorProps` spec to accept `droppedKey`
- document that parent provides `onSimulateDrop`
- show updated call to `getProcessedMetricInfo`
- `n/a`

Update inspector hook docs

---

src/ui/CardinalityCapsule.md

- document CardinalityCapsule UI organism

Add CardinalityCapsule spec

---

src/00-Overview.md

- clarify dispatch order in main Mermaid diagram with an `eventListeners` node

Update Mermaid dispatch chain

---

src/ui/DataPointInspectorDrawer.md

- document layout and props for DataPointInspectorDrawer
- describe tests and Storybook states

Add DataPointInspectorDrawer spec

---

src/logic/processing/jaccardEstimator.md

- flesh out `jaccardEstimator.md` spec with purpose and API
- outline algorithm, complexity, deps and consumers
- add example test cases for simple sets

Expand jaccard estimator spec

---

src/ui/atoms/CRingSvg.md
src/ui/atoms/CopyButton.md
src/ui/atoms/MiniBar.md
src/ui/atoms/RarityDot.md
src/ui/tokens.css.md

- document global CSS tokens
- link token documentation from atom specs

Document UI tokens

---

src/ui/organisms/MetricInstanceWidget.md

- document MetricInstanceWidget organism
- `npm test --silent -- -u` *(fails: react-scripts not found)*

Add MetricInstanceWidget spec

---

src/ui/molecules/AttributeRow.md
src/ui/organisms/ExemplarsZone.md
src/ui/organisms/RawJsonZone.md

- document AttributeRow molecule
- document RawJsonZone organism
- document ExemplarsZone organism

Add docs for inspector subcomponents

---

CHANGELOG.md

- document the project history in `CHANGELOG.md`
- include an *Unreleased* section and summarize version `0.1.0`
- note that entries should follow SemVer with `BREAKING:` markers when needed

Add CHANGELOG with initial release

---

src/services/eventBus.md

- document the event bus and its events
- describe `data.snapshot.progress` payload for long-running imports

Add eventBus progress payload spec

---

src/ui/organisms/ValueZone.md

- document ValueZone organism used in Data-Point Inspector

Add ValueZone spec

---

src/ui/organisms/ExemplarTimeline.md

- document ExemplarTimeline organism in `src/ui/organisms`

Add ExemplarTimeline spec

---

DATA-POINT-INSPECTOR-SCOPE.md
src/contracts/03-Data-Contracts.md

- clarify that filter button calls onAddGlobalFilter
- explain the callback in the data contracts
- note optional status for v1.1

Clarify filter callback

---

src/utils/findSeriesData.md

- document `findSeriesData` helper

Add findSeriesData utility spec

---

CLAUDE.md
src/01-Architecture-Principles.md
src/design/design-tokens.md
src/hooks/useInspectorProps.md
src/services/eventListeners.md
src/state/uiSlice.md
src/ui/atoms/SeriesMathChip.md
src/ui/organisms/AttributeZone.md
src/ui/organisms/CardinalityCapsule.md
src/ui/organisms/DataPointInspectorDrawer.md
src/ui/organisms/ExemplarsZone.md
src/ui/organisms/InspectorHeader.md
src/ui/organisms/RawJsonZone.md
tests/README.md

This PR adds comprehensive specifications for the Data Point Inspector components:
- Create CLAUDE.md with project overview and commands
- Document DataPointInspectorDrawer as the flagship component
- Add specifications for all UI organisms: AttributeZone, CardinalityCapsule, etc.
- Create specs for ExemplarsZone and RawJsonZone
- Enhance SeriesMathChip implementation details
- Document state management and callback flow
- Add centralized design token system
- Update architecture principles with import exceptions
- Create testing guide with harness documentation

Add comprehensive component specifications and documentation

---

src/ui/atoms/RarityDot.tsx
tsconfig.base.json
tsconfig.json

- add TypeScript configuration files
- fix comment in `RarityDot.tsx`
- `pnpm build` *(fails: vite not found)*

Add tsconfig for Vite React

---

.gitignore
package.json

- add runtime UI dependencies: clsx, lucide-react, react-window
- add testing libs to devDeps
- stop ignoring pnpm lock files
- `pnpm install` *(fails: EHOSTUNREACH)*

Add missing UI dependencies

---

package.json
tsconfig.json

- update tsconfig to use baseUrl and path alias
- include tests in TypeScript project
- add `pnpm run typecheck` script
- `pnpm run typecheck` *(fails: missing packages / network unreachable)*

Add strict tsconfig and typecheck script

---

tests/README.md

- update tests README to match existing test files
- remove stray prompt text
- `npx vitest run` *(fails: EHOSTUNREACH)*

Fix test docs

---

src/global.css
src/tokens.css

This PR merges the changes from PR #92 with resolved conflicts in global.css. It adds a comprehensive set of design tokens in tokens.css for UI consistency and theme management.

Merge PR #92: Define missing CSS design tokens

---

src/global.css
src/tokens.css

- declare complete set of design tokens in `src/tokens.css`
- import token variables in `src/global.css`
- `pnpm lint` *(fails: ESLint couldn't find config)*
- `pnpm build` *(fails: vite not found)*

Define missing CSS design tokens

---

README.md

- mention the required Node.js version
- recommend using `nvm`
- `pnpm lint` *(fails: ESLint couldn't find a configuration file)*

Update quick start instructions

---

src/data/dispatchToWorker.ts

- mark which worker each task uses
- if a worker crashes, resolve its tasks as parser errors
- `npm run lint` *(fails: ESLint couldn't find config)*
- `npx vitest run` *(fails: request to registry.npmjs.org/vitest failed: EHOSTUNREACH)*

Handle parser worker crash

---

package.json
pnpm-workspace.yaml

- specify pnpm in `package.json`
- add a pnpm workspace file
- `pnpm --version`

Add pnpm config

---

CLAUDE.md

- Add typecheck command
- Update technologies to reflect current usage
- Add reference to Code-Comment-Guide.md
- Update CI/CD section to include typecheck
- Preserve sections on project scope and objectives
This update reflects the current state of the project and aligns with recent changes in the codebase.
---

Update CLAUDE.md with current project details

---

README.md

- mention dark theme focus in README
- invite contributions for light theme or `prefers-color-scheme`
- `npx eslint . --ext .ts,.tsx,.js,.jsx,.md` *(fails: ESLint couldn't find a configuration)*
- `npx vitest run` *(fails: npm registry unreachable)*

Clarify dark theme in README

---

.github/workflows/ci.yml
.gitignore
README.md
eslint.config.js
package.json
tsconfig.json

This PR merges the changes from PR #91 to add minimal ESLint and TypeScript configurations. These changes provide a foundation for other PRs that depend on them.

Merge PR #91: Add minimal lint and TypeScript configs

---

src/data/StaticFileProvider.tsx
src/data/dispatchToWorker.ts
src/utils/randomId.ts
tests/randomId.test.ts

This PR resolves conflicts in PR #134 by adding the randomId helper function with crypto fallback and updating imports in relevant files.

Fix PR #134: Add randomId helper with crypto fallback

---

README.md
package.json
scripts/generate-design-tokens.js
src/design/design-tokens.ts

This PR resolves conflicts in PR #122 by adding the generate-design-tokens.js script, updating design-tokens.ts, and adding the script to package.json and README.md.

Fix PR #122: Add token generation script

---

src/index.tsx

- update `src/index.tsx` to call and document `registerEventListeners`
- `npm run lint` *(fails: Parsing error)*
- `npm run test:unit` *(fails: vitest: not found)*

Ensure global event listeners initialized

---

package.json
src/ui/atoms/InstrumentBadge.module.css
src/ui/atoms/InstrumentBadge.tsx
tests/InstrumentBadge.test.tsx

This PR resolves conflicts in PR #99 by implementing the InstrumentBadge component. Changes include:

Fix PR #99: Add InstrumentBadge component

---

src/data/StaticFileProvider.tsx
src/services/eventBus.ts
src/services/eventListeners.ts
src/state/metricsSlice.ts
tests/eventFlow.test.ts

This PR resolves conflicts in PR #175 (Fix PR #114/113) which standardizes event names across the application. Main changes include:

Merge PR #175: Align event names across services

---

src/data/StaticFileProvider.tsx
src/services/eventBus.ts
src/services/eventListeners.ts
src/services/eventTypes.ts
src/state/metricsSlice.ts
tests/eventFlow.test.ts

This PR resolves conflicts in PR #114/113 by standardizing event names across the application. Key changes include:

Fix PR #114/113: Align event names across services

---

src/ui/atoms/InstrumentBadge.tsx

- document InstrumentBadge with a file header
- `pnpm lint` *(fails: Parsing error)*

Add header doc for InstrumentBadge
