src/services/eventListeners.md

- document mitt event listeners in `src/services/eventListeners.md`
- `npm test --silent -- --watchAll=false` *(fails: react-scripts not found)*

Add eventListeners spec

---

src/01-Architecture-Principles.md

- clarify that there is no persisted state in v1.1

Document no persistence in v1.1

---

src/01-Architecture-Principles.md

- clarify that processing modules may import small synchronous helpers from `logic/workers/utils`
- `npm test -- --watchAll=false` *(fails: react-scripts not found)*

Update Architecture Principles

---

src/01-Architecture-Principles.md
tests/README.md

- document test helpers in tests/README
- reference tests README from Architecture Principles

docs: add testing overview

---

src/services/eventBus.md

- document the mitt-based event bus used by services
- list standard event names and example usage
- note the `busMock` helper for tests

Add event bus spec

---

src/utils/formatters.md

- document number formatter helpers in `src/utils/formatters.md`

Add formatter utilities spec

---

src/contracts/rawOtlpTypes.md

- document worker-only OTLP JSON interfaces

Add raw OTLP type summary

---

README.md

- add README for OTEL Metrics project
- include sections on Running Tests and Building for Production

Add README with test and build info

---

src/config/README.md
src/hooks/useInspectorProps.md

- document config constants
- reference `DEFAULT_THRESHOLD_HIGH` in `useInspectorProps`
- `grep -n DEFAULT_THRESHOLD_HIGH -n src/hooks/useInspectorProps.md`

Add config docs and update inspector hook

---

src/global.css

- add minimal CSS reset rules
- define design tokens for font and background
- clean up body defaults
- `npm run lint` *(fails: ESLint couldn't find config)*

Add global CSS variables and base styles

---

src/ui/atoms/InstrumentBadge.module.css
src/ui/atoms/InstrumentBadge.tsx
tests/InstrumentBadge.test.tsx

- add InstrumentBadge atom with CSS module
- create unit test for InstrumentBadge

Add InstrumentBadge component

---

src/ui/organisms/ExemplarsZone.tsx
src/ui/organisms/RawJsonZone.tsx

- update `ExemplarsZone` to use `copyValue` & `ariaLabel`
- update `RawJsonZone` to use `copyValue` via wrapper
- confirm `AttributeRow` already uses new props

Fix CopyButton prop usage

---

src/ui/organisms/AttributeZone.module.css
src/ui/organisms/AttributeZone.tsx
src/ui/organisms/DataPointInspectorDrawer.tsx
tests/AttributeZone.test.tsx

- reuse AttributeRow molecule in AttributeZone
- compute rarity percentage from series count
- simplify AttributeZone styles
- forward seriesCount from DataPointInspectorDrawer
- add AttributeZone tests

Refactor AttributeZone to use shared AttributeRow

---

src/hooks/useInspectorProps.ts

- wire inspector hook to `setDashboardFilter` action in store

Fix inspector global filter hook

---

src/contracts/either.ts
src/data/fileValidator.ts
src/logic/workers/utils/jsonSafeParse.ts

- add `Either` type contract
- refactor `jsonSafeParse` and `fileValidator` to use new type

Add shared Either type

---

CLAUDE.md
src/00-Overview.md
src/contracts/CHANGELOG.md
src/contracts/README.md

- add docs about TypeScript contracts
- update references to old data contracts doc
- `pnpm lint` *(fails: ESLint couldn't find configuration)*
- `pnpm test:perf` *(fails: perf-budget.js not found)*
- `pnpm build` *(fails: vite not found)*

Add contracts README and changelog

---

src/data/StaticFileProvider.tsx
src/services/eventBus.ts

- standardize event names for data and UI actions
- update `StaticFileProvider` to emit new canonical names
- `npm run lint` *(fails: ESLint couldn't find configuration file)*

Align event names across bus and emitters

---

.github/workflows/ci.yml
CHANGELOG.md
package.json

- remove stale `test:perf` command from package.json
- drop perf test step from CI
- note removal in CHANGELOG
- `pnpm lint` *(fails: ESLint couldn't find a config)*
- `pnpm test:unit -- --ci` *(fails: vitest not found)*

Remove unused perf test script

---

package.json
tsconfig.json
vite.config.js

This PR merges the changes from PR #97 with resolved conflicts in tsconfig.json and updated vite.config.js. It adds proper TypeScript configuration to work with Vite and adds the vite-tsconfig-paths plugin for improved path handling.

Merge PR #97: Add tsconfig and integrate with Vite

---

package.json
tsconfig.json
vite.config.js

- setup `tsconfig.json` at project root extending Vite defaults
- use `vite-tsconfig-paths` plugin and drop manual alias
- add plugin as a dev dependency
- `npm run lint` *(fails: ESLint couldn't find a config)*

Add tsconfig and integrate with Vite

---

src/ui/organisms/MetricInstanceWidget.tsx
tests/useInspectorProps.test.tsx

This PR merges the changes from PR #90 with resolved conflicts in MetricInstanceWidget.tsx. It updates the useInspectorProps hook to use setDashboardFilter instead of addFilter and adds regression tests for the hook.

Merge PR #90: Fix inspector hook filter and params

---

src/hooks/useInspectorProps.ts
src/ui/organisms/MetricInstanceWidget.tsx
tests/useInspectorProps.test.tsx

- use global ui context in MetricInstanceWidget
- wire inspector hook to `setDashboardFilter`
- add regression test for `useInspectorProps`
- `npm run lint` *(fails: missing ESLint config)*

Fix inspector hook filter and params

---

src/ui/organisms/AttributeZone.module.css
src/ui/organisms/AttributeZone.tsx

This PR merges the changes from PR #110 with resolved conflicts in AttributeZone.module.css and AttributeZone.tsx. It refactors AttributeZone to use the reusable AttributeRow molecule component, which improves code reuse and maintainability.

Merge PR #110: Use shared AttributeRow component

---

src/ui/organisms/AttributeZone.module.css
src/ui/organisms/AttributeZone.tsx

- refactor AttributeZone to use the reusable AttributeRow molecule
- adjust layout styles for the new row component

Use shared AttributeRow component

---

src/data/readFile.ts

- use `decompressGzip` in `readFileContent`
- update documentation references
- `npm run build` *(fails: vite: not found)*

Fix gzip decompression import

---

src/ui/organisms/MetricInstanceWidget.tsx

- clean up MetricInstanceWidget by removing the unused `snapshotId` prop

Remove unused snapshotId prop

---

.github/workflows/ci.yml
src/hooks/useInspectorProps.ts
src/ui/organisms/MetricInstanceWidget.tsx
tests/useInspectorProps.test.tsx

This PR fixes the CI workflow by removing the --frozen-lockfile flag from the pnpm install command. Since pnpm-lock.yaml is in .gitignore, we should not use the --frozen-lockfile flag in CI. This will fix the build failures on all PRs.

Fix CI workflow to not use --frozen-lockfile flag

---

src/App.tsx

- import and invoke `registerEventListeners` in `App`
- clean up listeners on unmount
- `npm run lint` *(fails: ESLint couldn't find config)*

Initialize event listeners on app mount

---

mkdocs.yml
src/02-Code-Comment-Guide.md

- add documentation for required TSDoc tags
- list `@purpose`, `@algorithm` and deprecated `@perfBudget`
- show examples of good and bad comments
- publish new doc in mkdocs navigation
- `pnpm lint` *(fails: couldn't find eslint.config.js)*
- `pnpm test:unit` *(fails: vitest not found and node_modules missing)*

Add TSDoc comment guide

---

src/data/dispatchToWorker.ts

- check for Worker + URL support when initializing parser workers
- fall back to synchronous parsing when workers aren't available
- no-op terminateAllParserWorkers when workers unsupported
- `npm run typecheck` *(fails: cannot find module 'react')*

Add worker support check with sync fallback

---

src/design/design-tokens.ts

- add a canonical docblock header to `design-tokens.ts`

Add canonical header to design tokens

---

src/hooks/useFocusTrap.ts
src/ui/organisms/DataPointInspectorDrawer.tsx

- add minimal `useFocusTrap` hook to manage focus trapping
- apply focus trap to `DataPointInspectorDrawer`
- `pnpm lint` *(fails: ESLint couldn't find configuration)*

Implement focus trapping in inspector drawer

---

src/data/StaticFileProvider.tsx

- sync comments in StaticFileProvider with event types
- `npm run lint` *(fails: ESLint couldn't find config)*
- `npm run typecheck` *(fails to find module 'react')*

Fix StaticFileProvider event docs

---

src/services/eventBus.ts

- remove `EventMap` type from the bus implementation
- import `EventTypes` for bus typing
- delete unused event declarations

Update event bus to use shared EventTypes

---

src/design/design-tokens.ts
src/design/tokens.css
src/ui/atoms/InstrumentBadge.module.css
src/ui/atoms/InstrumentBadge.tsx
tests/InstrumentBadge.test.tsx

- style instrument badges with Lucide icons
- add token-based background colors
- document props for InstrumentBadge
- verify icon rendering in tests

Add icons and tokens for instrument badge

---

src/contracts/types.ts
src/hooks/useInspectorProps.ts
src/ui/organisms/AttributeZone.tsx

- convert `onAddGlobalFilter` handler to build `key=value` text
- expand docs for the callback in the public types
- clarify callback description for `AttributeZone`

Update global filter callback

---

src/state/metricsSlice.ts
tests/metricsSlice.test.ts

- track snapshot loading and error state in metrics slice
- expose registerError and markLoading actions
- store loading/error states with snapshot actions
- add tests for metrics slice

Add loading/error tracking to metrics slice

---

src/index.tsx
src/state/metricsSlice.ts

- extend metrics slice with loading & error reducers
- re-enable event listeners in the app bootstrap
- `pnpm lint` *(fails: couldn't find eslint config)*
- `pnpm build` *(fails: vite not found)*

Add loading/error state tracking

---

src/global.css

- rely on imported design tokens instead of redefining them in `global.css`
- reference heading text color from tokens
- `npm run lint` *(fails: ESLint couldn't find a config)*

Clean up global styles

---

src/ui/molecules/AttributeRow.tsx
src/ui/organisms/AttributeZone.tsx
src/ui/organisms/DataPointInspectorDrawer.tsx
tests/AttributeZone.test.tsx

- confirm filter feature out-of-scope via project scope docs
- remove `onAddGlobalFilter` prop from `AttributeRow` and `AttributeZone`
- stop forwarding unused prop in `DataPointInspectorDrawer`
- update unit tests
- `npm run test:unit` *(fails: `vitest: not found`)*

Remove unused filter callback

---

src/ui/organisms/AttributeZone.tsx

- measure AttributeRow height on mount using `useRef`
- feed measured size to `FixedSizeList`

Measure AttributeRow height for virtual list

---

src/ui/organisms/AttributeZone.tsx
src/ui/organisms/CardinalityCapsule.tsx
tests/AttributeZone.test.tsx
tests/CardinalityCapsule.test.tsx

- make attribute rows keyboard accessible
- make mini-bar rows keyboard accessible
- test keyboard interaction for AttributeZone
- test keyboard interaction for CardinalityCapsule

Enable keyboard access for attribute rows

---

.storybook/main.ts
.storybook/preview.ts
README.md
package.json
src/ui/atoms/GaugeCard.stories.tsx

- add Storybook config using the Vite builder
- define simple GaugeCard stories
- expose `pnpm storybook` script and document usage
- `npx vitest run` *(fails: request to https://registry.npmjs.org/vitest failed, reason: connect EHOSTUNREACH)*

Add Storybook config and GaugeCard stories

---

src/ui/atoms/MiniBar.tsx

- update MiniBar to accept `value` and `max`
- keep CardinalityCapsule call site in sync
- `npm run typecheck` *(fails: Cannot find type definition file for 'node')*

Use value/max for MiniBar

---

tests/dispatchToWorker.test.ts
tests/seriesKeyEncoder.test.ts
tests/validateFile.test.ts

- add tests for validateFile covering extension checks and size limits
- mock Web Worker to test dispatchToParserWorker
- verify seriesKeyEncoder encode/decode round-trip
- `pnpm test:unit` *(fails: Invalid package manager specification)*

Add unit tests for file validation, worker dispatch, and key encoding

---

src/ui/atoms/CounterCard.tsx
src/ui/atoms/GaugeCard.tsx
src/ui/organisms/ExemplarsZone.tsx
src/utils/formatters.ts

- reorganize `formatters` as an object with helpers
- update CounterCard, GaugeCard and ExemplarsZone to use the new API
- `npm install` *(fails: no output)*

Refactor formatters into object

---

README.md
eslint.config.js
tsconfig.json

- add `eslint.config.js` with very basic rule
- add `tsconfig.json`
- mention running `pnpm lint` and `pnpm dev` in README
- `pnpm lint` *(fails: unable to parse TypeScript)*
- `pnpm dev` *(fails: vite not found)*

Add minimal lint and TypeScript configs

---

tests/README.md
tests/attributeStats.test.ts
tests/decompressGzip.test.ts
tests/exemplarExtractor.test.ts
tests/jaccardEstimator.test.ts
tests/jsonSafeParse.test.ts
tests/readFile.test.ts
tests/seriesCardinalityCalc.test.ts
tests/seriesKeyEncoder.test.ts
tests/uniqueValueCounter.test.ts

- add coverage for modules in `src/data`, worker utils and processing logic
- extend series key decoder tests
- document new tests in `tests/README.md`
- `pnpm i` *(fails: EHOSTUNREACH)*

Add unit tests for data and processing logic

---

.eslintrc.cjs
.eslintrc.json
package.json

- add `.eslintrc.json` describing cross-layer import restrictions
- expose legacy config through `.eslintrc.cjs`
- update `lint` script to use the new config
- `pnpm lint` *(fails: parsing errors)*

Add layer restrictions via ESLint

---

CLAUDE.md

- clarify that Node 18.17+ is required and pnpm is used for commands
- `pnpm lint` *(fails: Parsing error because dependencies missing)*
- `pnpm i` *(fails: EHOSTUNREACH registry.npmjs.org)*

Update CLAUDE development commands

---

src/ui/organisms/AttributeZone.module.css

- resolve merge conflict markers in `AttributeZone.module.css`
- keep `.list` class for attributes list style
- `npm run lint` *(fails: Parsing error)*

Fix leftover merge markers in AttributeZone.module.css

---

src/02-Code-Comment-Guide.md

- document new file header tag requirements
- note that `@perfBudget` is deprecated
- show example header block
- `pnpm lint` *(fails: parsing errors and missing node modules)*

Update code comment header docs

---

.github/workflows/ci.yml
README.md
package.json

- add `typecheck` npm script
- run type checking during CI
- document `pnpm typecheck` in README
- `pnpm typecheck` *(fails: Cannot find type definition file for 'node')*
- `pnpm lint` *(fails to parse test files)*
- `pnpm test:unit -- --ci` *(fails: vitest not found)*

Add typecheck script and CI check

---

src/utils/formatters.ts

- add a canonical header to `src/utils/formatters.ts`
- `pnpm lint` *(fails: node_modules missing)*

Add canonical header for formatters

---

.github/workflows/e2e.yml
playwright.config.ts
tests/README.md
tests/e2e/dataPointInspector.spec.ts
tests/fixtures/basic-snapshot.json

- configure Playwright with a preview server
- add a basic e2e spec and fixture
- install browsers in the e2e workflow
- document running e2e tests
- `pnpm test:e2e` *(fails: playwright not found)*

Add Playwright e2e setup

---

.github/workflows/ci.yml
package.json

- delete `test:perf` from `package.json`
- remove the unused perf test step from the CI workflow
- `pnpm lint` *(fails: node_modules missing)*

Remove perf test script

---

src/ui/atoms/CounterCard.tsx
src/ui/atoms/GaugeCard.tsx
src/ui/atoms/HistogramMiniChart.tsx

- add `data-testid` attributes to `GaugeCard`, `CounterCard` and `HistogramMiniChart`
- `pnpm test:unit` *(fails: vitest not found; node modules missing)*

Add data-testid attributes for metric cards

---

tests/e2e/drawerInteractions.spec.ts
tests/e2e/rawJsonCopy.spec.ts

- add drawer interactions test covering focus, drop simulation and ESC close
- add raw JSON view test verifying expand/collapse and copy functionality
- `pnpm test:e2e` *(fails: playwright not found)*

Add e2e tests for drawer interactions

---

.github/workflows/e2e.yml

- upload Playwright report and test results when E2E tests fail
- `pnpm lint` *(fails: cannot find dependencies)*

Add artifact upload for failed E2E runs

---

playwright.config.ts
tests/e2e/dataPointInspector.spec.ts
tests/e2e/fixtures.ts

- update Playwright defaults for screenshots, trace and video
- log browser console output per test
- `pnpm i` *(fails: EHOSTUNREACH)*

Add console log capture to Playwright tests
